name: my fitst workdflow job
on: workflow_dispatch
jobs: 
  my-first-workflow:
     runs-on: ubuntu-latest
     steps: 
       - name: Print greeting
         run: echo "hello world" 
       - name: Print goodbyee!
         run: echo "good byee"
