name: my fitst workdflow job
on: workflow_dispatch
jobs: 
  my-first-workflow:
     runs-on: ubuntu-latest
     steps: 
       - name: Print greeting
         run: |
            echo "First output"
            echo "Second output"
